Import numpy

In [8]:
import numpy as np

create an array with the structure
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```

call it `array`

In [9]:
array = np.array([[1, 6, 11],
       [2, 7, 12],
       [3, 8, 13],
       [4, 9, 14],
       [5, 10, 15]])

find the shape of the array

In [10]:
array.shape

(5, 3)

Select the 3rd column of the array

In [11]:
array[:,2]

array([11, 12, 13, 14, 15])

Create a vector with the numbres 15 to 55, call it array2 *(hint: use np.arange)*
*pista: usa np.arange*

In [19]:
array2 = np.arange(15, 56)

Assign the value `23` to the 5th position in array2

In [24]:
array2[4] = 23

reverse array2 *(that means `[55,54,....,15]`)*

In [33]:
array2 = array2[::-1]
print(array2)

[15 16 17 18 23 20 21 22 23 24 25 26 27 28 29 30 31 32 23 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


Create a diagonal matrix where the diagonal elements are the first 5 elements in even positions in array2 (so the 2nd, 4th, 6th, 8th and 10th element), call it `matrix_diag` *(hint: use np.diag)*

In [35]:
array3 = array2[1::2][:5]
print(array3)

[16 18 20 22 24]


In [36]:
matrix_diag = np.diag(array3)
print(matrix_diag)

[[16  0  0  0  0]
 [ 0 18  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 22  0]
 [ 0  0  0  0 24]]


print the dimensions of `matrix_diag`

In [39]:
matrix_diag.ndim

2

Create a matrix made out of random numbers shaped 5x3 (5 rows by 3 columns), call it `matrix`

In [38]:
matrix = np.random.random((5,3))
print(matrix)

[[0.79185211 0.60455209 0.46248571]
 [0.34248656 0.42461376 0.48116582]
 [0.15410005 0.98962495 0.39325712]
 [0.07828862 0.5539344  0.36759331]
 [0.97457809 0.16456452 0.34888699]]


multiply `matrix` by `matrix_diag`

In [41]:
matrix.T @ matrix_diag

array([[12.66963375,  6.164758  ,  3.08200098,  1.72234954, 23.38987424],
       [ 9.67283346,  7.64304759, 19.79249903, 12.18655671,  3.9495485 ],
       [ 7.39977135,  8.6609847 ,  7.8651425 ,  8.08705284,  8.37328785]])